DROP TABLE RepairJob;
DROP TABLE RepairPerson;
DROP TABLE CustomerBill;
DROP TABLE ServiceContract;
DROP TABLE Clusters;
DROP TABLE ServiceLineItem;
DROP TABLE Warranty;
DROP TABLE Cust;
DROP TABLE Machine;
